# Generated by Django 3.0.6 on 2021-01-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_salary', models.IntegerField()),
                ('emp_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='slot',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='trainer',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
