# Generated by Django 3.1.5 on 2021-01-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210124_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_number',
            field=models.CharField(max_length=12),
        ),
    ]
